version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/develop/django/Dockerfile
    volumes:
      - .:/app
    environment:
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
